### ISSUE TITLE
Testing on Windows required

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/JobSearchWebScraping#10]
Test script on Windows. Provide a report on your results.

**Comment by AniruddhaChattopadhyay** [comment]
@funbeedev Can You please assign this to me? I have worked with selenium before in windows.

**Comment by funbeedev** [comment]
Sure, assigned to you.

**Comment by funbeedev** [comment]
@AniruddhaChattopadhyay  any updates?

**Comment by AniruddhaChattopadhyay** [comment]
I sorry I am not in a position to do this due to some unfortunate circumstances at my end. I am really sorry for wasting your time.

**Comment by funbeedev** [comment]
no worries!

**Comment by feriodismo** [comment]
I was able to test in on Windows. No problem, but I have to add the '.exe' extension to the driver 'filename', I only tested on 'chromedriver'. If you want a more extended report I can help you.

**Comment by funbeedev** [comment]
@feriodismo Thanks for checking this! Could you create a PR updating the README with info on running on Windows?
Just create a new heading like "Running on Windows" and list any changes you had to make to get it to run.

**Comment by feriodismo** [comment]
good! let me check firefox too, and then I will update de README, thanks
