### ISSUE TITLE
Auto detect the browser driver to configure 

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/JobSearchWebScraping#11]
Script currently includes geckodriver configuration.

Make changes so both geckodriver and chromedriver are supported:
- Detect which driver is present in the same directory as script.
- If a file called chromedriver exists in directory, setup chromedriver
- If a file called geckodriver exists in directory, setup geckodriver
- If neither driver is detected print error message

**Comment by JoeAmedeo** [comment]
I would be willing to take this one on.

**Comment by funbeedev** [comment]
Of course. You're assigned now @JoeAmedeo
