### ISSUE TITLE
Add option to use headless mode for web driver

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/JobSearchWebScraping#14]
**Current Behaviour**
- When running the script the browsers will launch in GUI mode

**Changes requested**
- Add an option to run web driver in headless mode for both chromedriver and geckodriver
- To select headless mode the user should run the script using `python job-search-web-scraping.py headless`
- Update README.md with the info on how to run in headless mode

**Comment by asperduti** [comment]
Can I work on this?

**Comment by funbeedev** [comment]
sure, you're assigned now @asperduti
