### ISSUE TITLE
Fill in the location field when searching

### ISSUE THREAD

**Issue by funbeedev** [inspirezonetech/JobSearchWebScraping#6]
The script currently only fills in the job description field. Add code to fill in the location field also before starting the search.

**Comment by btapash** [comment]
Please assign this to me! @funbeedev

**Comment by btapash** [comment]
@funbeedev  I have earlier worked on news article scraping using beautifulsoup and request, I think I can work with selenium too.

**Comment by funbeedev** [comment]
Sure, I've assigned it to you.

**Comment by btapash** [comment]
@funbeedev , I have created a PR. Please review it! If you approve, could you assign me to the next issue that I asked you before?
